name: validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  synth:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install

    - name: Code style check
      run: poetry run black . --check

    - name: Code quality check
      run: poetry run ruff .

    - name: CDK synth
      run: |
        poetry run cdk synth
